### ISSUE TITLE
Test Adjusting Content Inset

### ISSUE THREAD

**Issue by nhgrif** [metova/MetovaBase#2]
`adjustContentInset(scrollview scrollView: UIScrollView, forKeyboardWillChangeFrameNotification notification: NSNotification)` has no unit tests.  It should be fully unit tested.

**Comment by lgauthier** [comment]
Looks like I added a test for this method back in May in this commit: ba340c80d44f854181f5daa6d73576cdfdecf838

Closing this issue super late...
